services:
  trend-bot:
    build: .
    container_name: crypto-trend-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - trend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



  mysql:
    image: mysql:8.0
    container_name: trend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - trend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:

networks:
  trend-network:
    driver: bridge